#!/usr/bin/perl -w
use strict;

#This program is used to generate a series of random sequences according to the given frequency of A,T,C,G

my ($out,$size,$len,$type)= @ARGV;
die "Error with arguments!\nusage: $0 <OUT file> <Sequence number> <Sequence Length> <dgr/crispr>\n" if (@ARGV<4);
open(OUT,">$out")||die("Can't write to $out\n");

my @base=('A','T','C','G');
my @freq=();
if($type eq "crispr"){
    @freq = (0.28,0.28,0.22,0.22);
}
else{
    @freq = (0.27,0.23,0.24,0.26);
}
#my @freq=(0.25,0.25,0.25,0.25);
my $buf = "";
srand;
for(my $i=1;$i<=$size;$i++){
    print OUT ">$i\n";
    my $seq="";
    for(my $j=1;$j<=$len;$j++){
	my $ran = int(rand(100));
	if($ran < $freq[0]*100){
	    $seq .= $base[0];
	}
	elsif($ran < ($freq[0]+$freq[1])*100){
	    $seq .= $base[1];
	}
	elsif($ran < ($freq[0]+$freq[1]+$freq[2])*100){
            $seq .= $base[2];
        }
	else{
	    $seq .= $base[3]
	}
    }
    print OUT "$seq\n";
}


close OUT;
#system("gzip $out");
exit;
